### PR TITLE
CI upgrade

### PR DESCRIPTION
**Pull request by ambrozic**

### CODE REVIEW

**Comment by cbaines** [comment]
It's most useful if the commit messages are in the present tense (e.g. "Add pyOpenSSL"), and include the motivation for the change, as its not immediately clear from your first commit why pyOpenSSL is being added (there is a Git styleguide here [1]).

1: https://github.com/alphagov/styleguides/blob/master/git.md

**Comment by ambrozic** [comment]
@cbaines fixed. thanks for a review.

**Comment by cbaines** [comment]
> @cbaines fixed. thanks for a review.

:+1: I see that Jenkins has now picked up this branch which is good, but the build has failed.

**Comment by ambrozic** [comment]
@cbaines yeah, it failed. will debug it as soon as we get access to https://ci.integration.publishing.service.gov.uk/

**Comment by cbaines** [comment]
> @cbaines yeah, it failed. will debug it as soon as we get access to https://ci.integration.publishing.service.gov.uk/

Have you got access issues with Jenkins itself, or with the CI agent over SSH?

**Comment by ambrozic** [comment]
access issues with jenkins/ci website because of vpn. should be resolved today evening.

**Pull request merged**
