### PR TITLE
Migrate dashboard views to ResourceView

### PR DESCRIPTION
**Pull request by leenagupte**
The aim is to enforce authorization on routes in one place through the ResourceView base class. To be able to do that, all views need to inherit from ResourceView.
The following views were updated to follow that pattern:
* ModuleType
* Module
* Dashboard
* User

ResourceView also needed updating to allow it to support modules and dashboards:
* Add a PUT method
* Change POST to only create new resources. Previously it was used to create and update.
* Allow the use of a different serialize method for list objects.
* Customise list ordering by passing an order_by field to the GET.
* Standardise how sub_resources are added so that they call methods on the child view. 

https://www.pivotaltracker.com/story/show/93451212

### CODE REVIEW

**Comment by mattrco** [comment]
Could you provide a description, and maybe a link to the pivotal story? Squashing the commits somewhat would also be good, particularly the ones that fail CI.

**Comment by leenagupte** [comment]
@mattrco I've added a description.  Hopefully it makes things a bit clearer.

**Comment by jabley** [comment]
Overall, :+1: :grin: 

Personally, I found it really hard to review at that size though.

Minor quibble about changing responses from 401 to 403, but I can live with that.

**Comment by mattrco** [comment]
:+1: for clear description

**Comment by jabley** [comment]
Meh. 401 -> 403 has broken smokey. I'll fix.

**Pull request merged**
