### PR TITLE
Add celery job queue to Stagecraft

### PR DESCRIPTION
**Pull request by tombooth**
We use django-celery because it provides us with a set of models for
controlling periodic jobs and the scheduler for celerybeat to execute
them.

This adds 3 new process types to the Procfile:
   - `worker` the process that will consume the jobs to be executed and
     run them. The `-E` tells the process to emit events that will be
     consumed by the celerycam process to store state of jobs
   - `beat` reads from the database and triggers scheduled periodic jobs
   - `celerycam` reads the state of running jobs periodically and stores
     this information in the database

### CODE REVIEW

**Comment by tombooth** [comment]
The environment specific config (BROKER_URL) is setup in https://github.gds/gds/alphagov-deployment/pull/1027

**Comment by jcbashdown** [comment]
Looks reasonable. What does success for this look like though? Just being able to run the manage commands?

**Comment by tombooth** [comment]
I had some tasks running locally on the GOV.UK dev vm, but I didn't want to commit a bunch of dummy tasks. I can add something if you want so we can create a periodic job in preview.

**Comment by tombooth** [comment]
@jcbashdown I've added a simple task that can be used to setup a periodic job in preview

**Pull request merged**
